# Generated by Django 5.1.1 on 2024-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tree_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(blank=True, to='api.event'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sources',
            field=models.ManyToManyField(blank=True, to='api.source'),
        ),
    ]
