# Generated by Django 5.1.1 on 2024-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_death_date_alter_person_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
