# Generated by Django 5.1.1 on 2024-09-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='api.person'),
            preserve_default=False,
        ),
    ]
