# Generated by Django 5.1.1 on 2024-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
